{{- if .Values.envoy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-mind.fullname" . }}-envoy
  labels:
    app: {{ include "kube-mind.fullname" . }}
spec:
  replicas: {{ .Values.envoy.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kube-mind.fullname" . }}-envoy
  template:
    metadata:
      labels:
        app: {{ include "kube-mind.fullname" . }}-envoy
        scrape-metrics: "true"
    spec:
      containers:
        - name: envoy
          image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 9901
              name: admin
          volumeMounts:
            - name: envoy-config-volume
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
      volumes:
        - name: envoy-config-volume
          configMap:
            name: {{ include "kube-mind.fullname" . }}-envoy-config
{{- end -}}
